# Generated by Django 4.0.1 on 2023-06-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0008_rename_post_id_postimagemapping_post_and_more'),
        ('core_comment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='core_post.post'),
        ),
    ]
