# Generated by Django 4.0.1 on 2023-06-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0002_comment_post_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_uuid',
            new_name='post_uiid',
        ),
    ]
