# Generated by Django 4.0.1 on 2023-06-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0003_rename_post_uuid_comment_post_uiid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_uiid',
        ),
    ]
