# Generated by Django 4.0.1 on 2023-06-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0005_remove_post_image_mapping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimagemapping',
            old_name='image_mapping',
            new_name='post_id',
        ),
    ]
