# Generated by Django 4.0.1 on 2023-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0007_alter_postimagemapping_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimagemapping',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AddField(
            model_name='postimagemapping',
            name='post_uuid',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
