# Generated by Django 4.0.1 on 2023-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0003_alter_comment_post'),
        ('core_post', '0008_rename_post_id_postimagemapping_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(related_name='posts', to='core_comment.Comment'),
        ),
    ]
